jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run pytest --version
          name: Test it
  
  python_lint:
    executor: python/default
    steps:
      - checkout
      - run:
          name: run black
          command: black pytext --check --diff
      - run:
          name: run isort
          command: |
              isort pytext --recursive --multi-line 3 --trailing-comma --force-grid-wrap 0 \
                  --line-width 88 --lines-after-imports 2 --combine-as --section-default THIRDPARTY --check-only
orbs:
  python: circleci/python@1.0.0
version: 2.1
workflows:
  main:
    jobs:
      - build
      - python_lint
